import {
    Quest as HackHubQuest,
    RegisterQuest,
    type QuestDialogDefinition,
} from "@hotbunny/hackhub-content-sdk";

import { Q10_OBJECTIVES } from "../../content/index.js";

// Direct quotes from the design doc's Q10 LOCKED FINAL v1.0 "Final Dialogue"
// scene (Daniel walks the player through the provenance gap). Trigger point
// still TODO. switchBranch/isEnd only — never onEnd/onSelect, see
// q03-quest.ts's Dialog field comment (permanently non-functional in this
// HackHub build, docs/bugs.md (entry 1)).
const Q10_DIALOG: QuestDialogDefinition = {
    main: [
        { speaker: "player", text: "Could the match have been changed?", audio: "", timeout: 3000 },
        { speaker: "Daniel", text: "Possibly.", audio: "", timeout: 3000 },
        { speaker: "player", text: "Can you tell?", audio: "", timeout: 3000 },
        { speaker: "Daniel", text: "Not from this record.", audio: "", timeout: 3000 },
        { speaker: "Daniel", text: "That's unusual.", audio: "", timeout: 3000 },
        { speaker: "player", text: "Why?", audio: "", timeout: 3000 },
        {
            speaker: "Daniel",
            text: "The resolver normally keeps the original source reference. This one doesn't.",
            audio: "",
            timeout: 3000,
        },
        { speaker: "player", text: "What does that mean?", audio: "", timeout: 3000 },
        {
            speaker: "Daniel",
            text: "It means we're looking at the transformed data. Not the evidence that produced it.",
            audio: "",
            isEnd: true,
        },
    ],
};

interface Q10QuestData {
    readonly locatePipelineArchiveDone: boolean;
    readonly inspectRawSourceDone: boolean;
    readonly traceEntityResolutionDone: boolean;
    readonly identifyProvenanceGapDone: boolean;
    readonly checkResolutionLogDone: boolean;
}

@RegisterQuest
export class EntityResolutionQ10Quest extends HackHubQuest<Q10QuestData> {
    override Name = "entity_resolution.q10";
    override Title = "THE FALSE CONNECTION";
    override Description =
        "The full entity-resolution pipeline reveals SUBJECT-88172 was generated by the resolution step itself, at 0.67 confidence.";
    override Group = "storyline" as const;
    override AutoStart = false;
    override AutoComplete = true;
    override QuestsToComplete = ["entity_resolution.q09"];
    override Rewards = { money: 0, xp: 0 };
    override Dialog = Q10_DIALOG;
    override Objectives = Q10_OBJECTIVES;

    override CreateData(): Q10QuestData {
        return {
            locatePipelineArchiveDone: false,
            inspectRawSourceDone: false,
            traceEntityResolutionDone: false,
            identifyProvenanceGapDone: false,
            checkResolutionLogDone: false,
        };
    }

    override OnStart() {
        // TODO: implement — see docs/source-current.md.
    }

    override OnObjectivesStart() {
        // TODO: wire event handlers — see command mapping in content/q10.ts.
    }

    override OnComplete() {
        // TODO: implement. Needs, per Q10_REWARDS:
        //   gameRuntime.reward.claim(... locateArchive, 15)
        //   gameRuntime.reward.claim(... inspectRawSource, 20)
        //   gameRuntime.reward.claim(... identifyCandidate, 15)
        //   gameRuntime.reward.claim(... traceResolution, 20)
        //   gameRuntime.reward.claim(... identifyConfidence067, 10)
        //   gameRuntime.reward.claim(... traceGeneratedRelationship, 15)
        //   gameRuntime.reward.claim(... identifyIncompleteProvenance, 15)
        //   gameRuntime.reward.claim(... correctlyReconstruct, 10)
        //   gameRuntime.reward.claim(... checkLog, 10) — if checkResolutionLog done
        //   Bank.transaction(... Q10_REWARDS.money)
        //   gameRuntime.flagStore.set(Q10_FINAL_STATE_FLAG, true)
    }

    override OnAbandon() {
        // TODO: implement.
    }
}
