// SKELETON — see docs/phase13-q04-q16-design-recovered.md. Mail, dialogue,
// HackhubPost, network fixtures NOT YET WRITTEN.

import { asId } from "../core/index.js";
import { flagEquals } from "../domain/shared/index.js";
import type { Quest } from "../domain/quest/index.js";

export { Q10_ROOT_FILES } from "./q10-filesystem.js";

// TODO: target/archive location not yet decided.

export const Q10_OBJECTIVE_IDS = {
    locatePipelineArchive: "q10.objective.01",
    inspectRawSource: "q10.objective.02",
    traceEntityResolution: "q10.objective.03",
    identifyProvenanceGap: "q10.objective.04",
    checkResolutionLog: "q10.objective.04b", // optional
} as const;

export const Q10_OBJECTIVES = [
    { name: Q10_OBJECTIVE_IDS.locatePipelineArchive, description: "Locate the pipeline archive" }, // tool: ssh + ls (native)
    {
        name: Q10_OBJECTIVE_IDS.inspectRawSource,
        description: "Inspect the raw COM-07-88421 source", // tool: cat (native)
        unlocksAfter: [Q10_OBJECTIVE_IDS.locatePipelineArchive],
    },
    {
        name: Q10_OBJECTIVE_IDS.traceEntityResolution,
        description: "Trace the entity-resolution step (PERSON-19382 -> SUBJECT-88172, 0.67, ACCEPT)", // tool: sqlmap (native)
        unlocksAfter: [Q10_OBJECTIVE_IDS.inspectRawSource],
    },
    {
        name: Q10_OBJECTIVE_IDS.identifyProvenanceGap,
        description: "Reconstruct relationship creation and identify the provenance gap", // tool: sqlmap (native)
        unlocksAfter: [Q10_OBJECTIVE_IDS.traceEntityResolution],
    },
    {
        name: Q10_OBJECTIVE_IDS.checkResolutionLog,
        description: "Check the resolution log for the accept decision", // tool: sqlmap (native)
        unlocksAfter: [Q10_OBJECTIVE_IDS.identifyProvenanceGap],
    },
];

export const Q10_REPLAY_OBJECTIVES = Q10_OBJECTIVES.map(
    ({ unlocksAfter: _unlocksAfter, ...objective }) => objective,
);

// XP breakdown per the design doc, best-effort mapped to objectives (9 XP
// items against 5 objectives — not objective-keyed).
export const Q10_REWARDS = {
    locateArchive: 15, // locatePipelineArchive
    inspectRawSource: 20, // inspectRawSource
    identifyCandidate: 15, // inspectRawSource
    traceResolution: 20, // traceEntityResolution
    identifyConfidence067: 10, // traceEntityResolution
    traceGeneratedRelationship: 15, // identifyProvenanceGap
    identifyIncompleteProvenance: 15, // identifyProvenanceGap
    correctlyReconstruct: 10, // identifyProvenanceGap
    checkLog: 10, // checkResolutionLog
    money: 650,
} as const;

export const Q10_FINAL_STATE_FLAG = "entity_resolution.q10.completed";
export const Q10_PIPELINE_ARCHIVE_FOUND_FLAG = "entity_resolution.q10.pipeline_archive_found";
export const Q10_ENTITY_RESOLUTION_FOUND_FLAG = "entity_resolution.q10.entity_resolution_found";
export const Q10_RELATIONSHIP_GENERATED_BY_RESOLUTION_FLAG =
    "entity_resolution.q10.relationship_generated_by_resolution";
export const Q10_ENTITY_MATCH_CONFIDENCE_FLAG = "entity_resolution.q10.entity_match_confidence"; // value: 0.67
export const Q10_SOURCE_PROVENANCE_INCOMPLETE_FLAG = "entity_resolution.q10.source_provenance_incomplete";
export const Q10_RESOLUTION_LOG_CHECKED_FLAG = "entity_resolution.q10.resolution_log_checked";
export const Q10_RESOLUTION_DECISION_FOUND_FLAG = "entity_resolution.q10.resolution_decision_found";

// Campaign-wide flags: TODO (new, not yet in flags.ts) —
// daniel_pipeline_understood, daniel_accountability_increased.

// No mail content found for Q10 in this pass — its "Objective 01" opening
// is Daniel speaking in person ("I checked COM-07 after you left...") with
// no Subject/mail framing, and the raw pipeline/entity-resolution data that
// follows is filesystem-fixture content already covered by the parallel
// filesystem-extraction fork (Q10_ROOT_FILES). No report-template, hold
// mail, completion mail, or HackhubPost teaser found either. TODO when Q10
// becomes the active implementation target.

export const Q10_THE_FALSE_CONNECTION: Quest = {
    id: asId<"Quest">("entity_resolution.q10"),
    chapterId: "chapter-03-false-positive", // provisional, see design doc
    title: "THE FALSE CONNECTION",
    description:
        "The full entity-resolution pipeline reveals SUBJECT-88172 was generated by the resolution step itself, at 0.67 confidence.",
    objectives: [
        {
            id: "q10.runtime.completion",
            description: "Q10 canonical completion boundary.",
            condition: flagEquals(Q10_FINAL_STATE_FLAG, true),
        },
    ],
};
